### ISSUE TITLE
SQL table creation  (user_agent)

### ISSUE THREAD

**Issue by Frederic-P** [Daniel-KM/Omeka-S-module-Comment#1]
When installing the Comment module for Omeka S I run into an error message:
"Omeka S encountered an Error"

I looked in the SQL-code and saw that the comment table never got created, so figured that the 'bug' must be in the SQL-part or before of the Module.php file. On inspecting the Create Table command I noticed that the user_agent was set to an excessively large Varchar; this is currently on line 94 of module.php:
`user_agent varchar(65535) NOT NULL,`

Pasting the code in PHPmyadmin revealed that this was indeed a possible error saying that:

`#1074 - Column length too big for column 'user_agent' (max=16383); use BLOB or TEXT instead`

I modified the SQL code to: 
`user_agent TEXT NOT NULL,`

This allowed the module to be installed; so far I haven't found any bugs introduced by this change.

**Technical Information**
OS: Ubuntu 16.04 (LTS) 64 Bit running in VM
Omeka Version: V1.1.1
Comment Version: V3.1.4
PHP 7.0.28-0ubuntu0.16.04.1
Apache/2.4.18 (Ubuntu)

**Odd detail**
The comment module installed without problems on a windows-hosted instance of Omeka S.

**Comment by Daniel-KM** [comment]
Thanks. The sql is created by Doctrine, so I didn't change it. I choose this size for compatibility with the plugin for Omeka Classic (for people who will upgrade their install), that uses 255 characters (not enough). Any size bigger works fine. So, I 'm going to update the plugin to use "text" instead of "varchar".

**Comment by Daniel-KM** [comment]
Fixed.
