### ISSUE TITLE
Possible Cross-Site Scripting vulnerability found Injectable request

### ISSUE THREAD

**Issue by iosdevelop** [Daniel-KM/Omeka-S-module-Comment#2]
The comment module is not escaping the $comment->body in the administrative view.  I think adding $escape() fixes this issue.

admin/comment/browse.html

Line 133 `<?php echo $escape(substr($comment->body(), 0, 200)); ?>`

without this I was able to inject `'"--></style></sCriPt><sCriPt>alert(15551474.19247)</sCriPt>`

**Comment by Daniel-KM** [comment]
Ok, thanks, it's committed.
