### ISSUE TITLE
Error installing newest version, comment table already exists

### ISSUE THREAD

**Issue by GitByrd** [Daniel-KM/Omeka-S-module-Comment#4]
Hi, I received an error upgrading to the newest version of this module on our site which has existing comments from the older version. The error said a table already exists in the database called comment. I thought maybe there was a duplicate and deleted the table on the test site and then it worked...however, it erased all of the previous comments made in the database. Is anyone else getting this error?

**Comment by Daniel-KM** [comment]
The upgrade process does not create a new table, the original one is kept. So I'm not sure that is related to the new version, and it's something hard to define.

**Comment by Daniel-KM** [comment]
This is fixed in new versions (check if the module Generic is installed and up to date else).
